version: '3'
services: 
    api:
        container_name: djangoapi
        build: ./api
        volumes:
             - type: bind
               source: "./api"
               target: "/api"
        command: python manage.py runserver 0.0.0.0:8000
        expose:
             - 8000
    nginx:
        build: ./nginx
        ports:
          - 80:80
        depends_on:
          - api
#     frontend:
#         build: ./frontend
#         volumes:
#           - node_modules_volume:/frontend/node_modules
#           - type: bind
#             source: "./frontend"
#             target: "/frontend"
#         command: yarn start
#         environment: 
#            - CHOKIDAR_USEPOLLING=true
#         ports:
#           - 3000:3000
        
# volumes:
#   node_modules_volume:
