version: '3'
services: 
    # api:
    #     build: ./api
    #     volumes:
    #          - type: bind
    #            source: "./api"
    #            target: "/api"
    #     command: python manage.py runserver 0.0.0.0:8000
    #     ports:
    #          - 8000:8000
    # nginx:
    #     build: ./nginx
    frontend:
        build: ./frontend
        volumes:
          - node_modules_volume:/frontend/node_modules
          - type: bind
            source: "./frontend"
            target: "/frontend"
        command: yarn start
        environment: 
           - CHOKIDAR_USEPOLLING=true
        ports:
          - 3000:3000
        
volumes:
  node_modules_volume:
